# Generated by Django 5.2.8 on 2025-11-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoround',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
