# Generated by Django 5.2.8 on 2025-11-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoapp', '0002_lottoround_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottoentry',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottoapp.lottoround'),
        ),
    ]
