# Generated by Django 5.2.8 on 2025-11-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottoapp', '0003_alter_lottoentry_round'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentRound',
        ),
    ]
