# Generated by Django 5.2.8 on 2025-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottoapp', '0004_delete_currentround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottoround',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lottoround',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lottoround',
            name='winning_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
